Revert "New value types for Calendar, TimeZone, and Locale"
This reverts commit 5178fd4c1dd4b2ee371b49a48f47252f92958bf5.

This breaks swift-ci for everyone:

stdlib/public/SDK/Foundation/Calendar.swift:426:74: error: 'DateInterval' is only available on iOS 10.0 or newer
    public func dateInterval(of component: Component, for date: Date) -> DateInterval? {