Revert "New value types for Calendar, TimeZone, and Locale"
This reverts commit 9ffd6ce9ca02857aa6db1f5e6496c6234a5a7387.

This broke Swift CI, OSS incremental RA:

./swift/stdlib/public/SDK/Foundation/TimeZone.swift:228:45: error: 'NSTimeZone' is not implicitly convertible to 'TimeZone'; did you mean to use 'as' to explicitly convert?
        return lhs._wrapped.isEqual(to: rhs._wrapped)